[tox]
envlist = py36, py37, py38, py39, flake8, examples

[travis]
python =
    3.9: py39
    3.8: py38
    3.7: py37, flake8, examples
    3.6: py36

# Test examples notebook
[testenv:examples]
basepython = python
deps = nbmake
commands = pytest --nbmake examples/energy_decay_curves_and_reverberation_time.ipynb


[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 roomacoustics

# Release tooling
[testenv:build]
basepython = python3
skip_install = true
deps =
    wheel
    setuptools
commands =
	python setup.py -q sdist bdist_wheel


[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
; If you want to make tox run the tests with the same versions, create a
; requirements.txt with the pinned versions and uncomment the following line:
;     -r{toxinidir}/requirements.txt
commands =
    pip install -U pip
    py.test --basetemp={envtmpdir}
